### ISSUE TITLE
Sass @extend misbehaving after upgrade

### ISSUE THREAD

**Issue by quarteris** [arsduo/koala#485]
Hi,

After the upgrade from Koala v. 2.0.3 to v. 2.0.4, we've discovered that @extend stopped working correctly. When a class is extended, its appearances under :not() are extended as well, which did not happen in v. 2.0.3. Look at this example:
```scss
.ic32 {
...
}

#collector_right { 
 a:not(.ic32) { clear: both; display: block; }
...
}

.rateIcon:before,.rateIconN:before {
@extend .ic32;
}
```

Difference in the output between versions:
![imgo](https://cloud.githubusercontent.com/assets/11520331/9483513/be2f1038-4ba1-11e5-86f8-09cdfc9067bd.jpg)

Looks like a compiler bug.
